const products = [
    {
        id: 1,
        name: 'Basic Tee',
        imageSrc: 'https://images.pexels.com/photos/341523/pexels-photo-341523.jpeg?auto=compress&cs=tinysrgb&w=600',
        imageAlt: 'Front of men\'s Basic Tee in black.',
        href: '#',
        color: 'Black',
        price: '$35',
      },
      {
        id: 2,
        name: 'Running Shoes',
        imageSrc: 'https://images.pexels.com/photos/335257/pexels-photo-335257.jpeg?auto=compress&cs=tinysrgb&w=600',
        imageAlt: 'Running shoes with cushioning and support.',
        href: '#',
        color: 'Blue',
        price: '$80',
      },
      {
        id: 3,
        name: 'Casual Backpack',
        imageSrc: 'https://images.pexels.com/photos/821651/pexels-photo-821651.jpeg?auto=compress&cs=tinysrgb&w=600',
        imageAlt: 'Stylish casual backpack for everyday use.',
        href: '#',
        color: 'Gray',
        price: '$50',
      },
      {
        id: 4,
        name: 'Wrist Watch',
        imageSrc: 'https://images.pexels.com/photos/248412/pexels-photo-248412.jpeg?auto=compress&cs=tinysrgb&w=600',
        imageAlt: 'Elegant wrist watch with leather strap.',
        href: '#',
        color: 'Brown',
        price: '$120',
      },
      {
        id: 5,
        name: 'Sunglasses',
        imageSrc: 'https://images.pexels.com/photos/2533266/pexels-photo-2533266.jpeg?auto=compress&cs=tinysrgb&w=600',
        imageAlt: 'Stylish sunglasses with UV protection.',
        href: '#',
        color: 'Black',
        price: '$40',
      },
      {
        id: 6,
        name: 'Laptop Sleeve',
        imageSrc: 'https://images.pexels.com/photos/3819969/pexels-photo-3819969.jpeg?auto=compress&cs=tinysrgb&w=600',
        imageAlt: 'Protective laptop sleeve with soft interior.',
        href: '#',
        color: 'Gray',
        price: '$25',
      },
      {
        id: 7,
        name: 'Water Bottle',
        imageSrc: 'https://images.pexels.com/photos/4202325/pexels-photo-4202325.jpeg?auto=compress&cs=tinysrgb&w=600',
        imageAlt: 'Stainless steel water bottle.',
        href: '#',
        color: 'Silver',
        price: '$15',
      },
      {
        id: 8,
        name: 'Headphones',
        imageSrc: 'https://images.pexels.com/photos/3270223/pexels-photo-3270223.jpeg?auto=compress&cs=tinysrgb&w=600',
        imageAlt: 'Noise-cancelling over-ear headphones.',
        href: '#',
        color: 'Black',
        price: '$100',
      },
    ];
  export default products